# Use the official PostgreSQL image from the Docker Hub
FROM postgres:16.2-bookworm

# Set environment variables (replace with your own values)
ENV POSTGRES_DB=Urban_Farm_Monitoring
ENV POSTGRES_USER=admin
ENV POSTGRES_PASSWORD="admin(very-strong-password)"

# Expose the PostgreSQL port
EXPOSE 5432