apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestion-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-ingestion-api
  template:
    metadata:
      labels:
        app: data-ingestion-api
    spec:
      containers:
      - name: data-ingestion-api
        image: mohammedaddi/data_ingestion_api:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: data-ingestion-api-service
spec:
  selector:
    app: data-ingestion-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
