apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-storage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-storage-service
  template:
    metadata:
      labels:
        app: data-storage-service
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: POSTGRES_DB
          value: "Urban_Farm_Monitoring"
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: data-storage-service
spec:
  selector:
    app: data-storage-service
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
