apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-analysis-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-analysis-service
  template:
    metadata:
      labels:
        app: data-analysis-service
    spec:
      containers:
      - name: data-analysis-service
        image: alexisbagot/data-analysis-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8501  # Assurez-vous que c'est le bon port pour Streamlit
        env:
        - name: DATABASE_HOST
          value: data-storage-service
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: POSTGRES_DB
          value: "data-storage-db"

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  selector:
    app: data-analysis-service
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: NodePort
