CREATE TABLE IF NOT EXISTS Sensors (
    ID INTEGER PRIMARY KEY,
    Provider VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS Plants (
    ID INTEGER PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS Measurements (
    ID INTEGER PRIMARY KEY,
    Sensor_ID INTEGER REFERENCES Sensors(ID),
    Plant_ID INTEGER REFERENCES Plants(ID),
    Temperature FLOAT,
    Humidity FLOAT,
    Timestamp TIMESTAMP
);